### ISSUE TITLE
exec: "/bin/echo": stat /bin/echo: no such file or directory

### ISSUE THREAD

**Issue by tomfotherby** [tianon/dockerfiles#12]
I found the `tianon/true` container from https://github.com/docker/compose/issues/942 - I'm trying to use it as a data-container workaround.

The first time I do `docker-composer up` things are fine, but subsequent `ups`, I get this error:

```
Recreating blah_data_1...
Cannot start container 4f0614f43cd4fe97e29b37bfde416edb1c38ec4cfe38a89b18838058ec3effe5: exec: "/bin/echo": stat /bin/echo: no such file or directory
```

Did you ever get this problem? I'm using `docker-compose` v1.1.0 and docker v1.5.0. (I also tried with `docker-compose` v1.2.0rc2 without luck)

yml file extract:
```
data:
   image: tianon/true
   volumes:
    - /local/file/path:/var/www/myapp

web:
  image: mycompany/myimage
  command: apache2 -D FOREGROUND
  volumes_from:
   - data
```
